name: CI/CD for Flask App

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install AWS CLI
        run: |
          sudo apt-get install -y awscli

      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-2'
          INSTANCE_PUBLIC_IP: '3.39.255.67'
          USERNAME: 'ubuntu'

        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

          echo "Deploying to AWS EC2..."
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USERNAME@$INSTANCE_PUBLIC_IP << 'EOF'
            cd /home/ubuntu/SWP-project-main  # 프로젝트 경로로 이동
            git checkout .  # 로컬 변경 사항 버리기
            git pull origin master  # 최신 코드 가져오기
            source /home/ubuntu/SWP-project-main/myenv/bin/activate  # 가상 환경 활성화
            pip install -r requirements.txt  # 의존성 설치
            pm2 restart flask-app  # Flask 애플리케이션 재시작
          EOF

          rm private_key.pem
